# Nome da aplicação
spring.application.name=projeto

# URL de conexão com o MySQL.
# Cria o banco caso ele não exista.
# serverTimezone define o fuso horário utilizado na conexão.
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

# Usuário do MySQL
spring.datasource.username=sergio

# Senha do MySQL
spring.datasource.password=livia

# Driver utilizado para conectar ao MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cria novamente as tabelas ao iniciar a aplicação
spring.jpa.hibernate.ddl-auto=create

# Exibe os comandos SQL no console
spring.jpa.show-sql=true

# Formata os comandos SQL exibidos no console
spring.jpa.properties.hibernate.format_sql=true

# Define o dialeto do Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect